server:
  port: 9001

spring:
  config:
    activate:
      on-profile:

  jpa:
    hibernate:
      ddl-auto:
      naming:
        physical-strategy:
    properties:
      hibernate:
        show_sql:
        format_sql:
    open-in-view: false

  datasource:
    driver-class-name:
    url:
    username:
    password:

jwt:
  redirect-url:
  token:
    secretKey:

notification:
  mattermost:
    enabled:
    webhook-url:
    channel :