server:
  port: 9001

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forest?serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

jwt:
  redirect-url: https://localhost:3000/login/success
  token:
    secretKey: Q4NSl604sgyHJj1qwEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSF4XXyYJkal13eqgB0F7Bq4HQ4NSl604sgyHJj1qwEkR3ycUeR4uUAt7WJraD7EN3O9DVM4yyYuHxMEbSF4XXyYJkal13eqgB0F7Bq4H # {secretKey} 로 만들기

notification:
  mattermost:
    enabled: true
    webhook-url: https://meeting.ssafy.com/hooks/j85wn7zntjbnjper47prr5icic
    channel :