pipeline {
    agent any
    options {
        timeout(time: 1, unit: 'HOURS') // set timeout 1 hour
    }
    environment {
        DOCKER = 'sudo docker'

        TIME_ZONE = 'Asia/Seoul'
        PROFILE = 'local'
        
        // REPOSITORY_CREDENTIAL_ID = 'adcdm77@naver.com'
        // REPOSITORY_URL = 'git@lab.ssafy.com:s08-final/S08P31B105.git'
        // TARGET_BRANCH = 'production-auth'
        
        // CONTAINER_NAME = 'prod-auth-container'
        
        // AWS_CREDENTIAL_NAME = 'choi1087'
        // ECR_PATH = '240177199888.dkr.ecr.ap-northeast-2.amazonaws.com/forest-back-auth'
        // IMAGE_NAME = '240177199888.dkr.ecr.ap-northeast-2.amazonaws.com/forest-back-auth'
        REGION = 'ap-northeast-2'
    }
    stages{

        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('env setting') {
            steps{
                sh 'cp /var/jenkins_home/env/auth/application-prod.yml /var/jenkins_home/workspace/prod-back-auth/forest-back/forest-auth/src/main/resources'                
            }            
        }
        
        stage('dockerizing project by dockerfile') {
            steps {
                dir('forest-back/forest-auth') {
                    sh '''
                ls -al
                chmod +x ./gradlew
                ./gradlew build
        		 docker build -t ${IMAGE_NAME_AUTH}:$BUILD_NUMBER .
        		 docker tag ${IMAGE_NAME_AUTH}:$BUILD_NUMBER ${IMAGE_NAME_AUTH}:latest
        		 '''
                }                
            }
            post {
                success {
                    echo 'success dockerizing project'
                }
                failure {
                    error 'fail dockerizing project' // exit pipeline
                }
            }
        }
        stage('upload aws ECR') {
            steps {
                script{
                    // cleanup current user docker credentials
                    sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'
                                       
                    docker.withRegistry("https://${ECR_PATH_AUTH}", "ecr:${REGION}:${AWS_CREDENTIAL_NAME}") {
                      docker.image("${IMAGE_NAME_AUTH}:${BUILD_NUMBER}").push()
                      docker.image("${IMAGE_NAME_AUTH}:latest").push()

                      sleep 10
                    }

                }
            }
            post {
                success {
                    echo 'success upload image'
                    sh 'docker rmi ${IMAGE_NAME_AUTH}:${BUILD_NUMBER}'
                    sh 'docker rmi ${IMAGE_NAME_AUTH}:latest'
                }
                failure {
                    error 'fail upload image'
                    sh 'docker rmi ${IMAGE_NAME_AUTH}:${BUILD_NUMBER}'
                    sh 'docker rmi ${IMAGE_NAME_AUTH}:latest'
                }
            }
        }

        stage('Manifest Update') {
            steps {
                git credentialsId: "${GIT_CREDENTIALS_ID}",
                    url: "${GIT_URL}",
                    branch: 'main'                
                
                dir('back') {
                    sh """
                    ls -al                    

                    cat ${EKS_DEPLOY_AUTH_YML} | grep image

                    sed -i 's|image: .*|image: "${IMAGE_NAME}:${currentBuild.number}"|' ${EKS_DEPLOY_AUTH_YML}
                    cat ${EKS_DEPLOY_AUTH_YML} | grep image
                    
                    git status
                    git add ${EKS_DEPLOY_AUTH_YML}
                    git commit -m '[UPDATE] forest-back-auth ${currentBuild.number} image versioning'
                    git push origin main
                    """
                }
            }
        }

    }
}
