version: "3"
services:
  application:
    image: ${FOREST_STUDY_IMAGE}
    container_name: ${FOREST_STUDY_CONTAINER}
    environment:
      KEY_STORE: ${KEY_STORE}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
      KEY_STORE_TYPE: ${KEY_STORE_TYPE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MM_WEBHOOK_URL: ${MM_WEBHOOK_URL}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      KAKAO_AUTHORIZATION_GRANT_TYPE: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
      KAKAO_CLIENT_NAME: ${KAKAO_CLIENT_NAME}
      KAKAO_CLIENT_AUTHENTICATION_METHOD: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
      JWT_REDIRECT_URI: ${JWT_REDIRECT_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - 9012:9012
    restart: always
