pipeline {
    agent any
    options {
        timeout(time: 1, unit: 'HOURS') // set timeout 1 hour
    }
    environment {
        DOCKER = 'sudo docker'

        TIME_ZONE = 'Asia/Seoul'
        PROFILE = 'local'
        
        REPOSITORY_CREDENTIAL_ID = 'adcdm77@naver.com'
        REPOSITORY_URL = 'git@lab.ssafy.com:s08-final/S08P31B105.git'
        TARGET_BRANCH = 'production-study'
        
        CONTAINER_NAME = 'prod-study-container'
        
        AWS_CREDENTIAL_NAME = 'choi1087'
        ECR_PATH = '240177199888.dkr.ecr.ap-northeast-2.amazonaws.com/forest-back-study'
        IMAGE_NAME = '240177199888.dkr.ecr.ap-northeast-2.amazonaws.com/forest-back-study'
        REGION = 'ap-northeast-2'
    }
    stages{

        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('env setting') {
            steps{
                sh 'cp /var/jenkins_home/env/study/application-prod.yml /var/jenkins_home/workspace/prod-back-study/forest-back/forest-study/src/main/resources'                
            }            
        }
        
        stage('dockerizing project by dockerfile') {
            steps {
                dir('forest-back/forest-study') {
                    sh '''
                ls -al
                chmod +x ./gradlew
                ./gradlew build
        		 docker build -t $IMAGE_NAME:$BUILD_NUMBER .
        		 docker tag $IMAGE_NAME:$BUILD_NUMBER $IMAGE_NAME:latest

        		 '''
                }                
            }
            post {
                success {
                    echo 'success dockerizing project'
                }
                failure {
                    error 'fail dockerizing project' // exit pipeline
                }
            }
        }
        stage('upload aws ECR') {
            steps {
                script{
                    // cleanup current user docker credentials
                    sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'
                    
                   
                    docker.withRegistry("https://${ECR_PATH}", "ecr:${REGION}:${AWS_CREDENTIAL_NAME}") {
                      docker.image("${IMAGE_NAME}:${BUILD_NUMBER}").push()
                      docker.image("${IMAGE_NAME}:latest").push()

                      sleep 10
                    }

                }
            }
            post {
                success {
                    echo 'success upload image'
                    sh 'docker rmi ${IMAGE_NAME}:${BUILD_NUMBER}'
                    sh 'docker rmi ${IMAGE_NAME}:latest'
                }
                failure {
                    error 'fail upload image' // exit pipeline
                    sh 'docker rmi ${IMAGE_NAME}:${BUILD_NUMBER}'
                    sh 'docker rmi ${IMAGE_NAME}:latest'
                }
            }
        }

        stage('Manifest Update') {
            steps {
                git credentialsId: 'my-key',
                    url: 'git@github.com:choi1087/forest_yaml.git',
                    branch: 'main'
                
                
                dir('back') {
                    sh """
                    ls -al                    

                    cat eks-deploy-study.yml | grep image

                    sed -i 's|image: .*|image: "${IMAGE_NAME}:${currentBuild.number}"|' eks-deploy-study.yml

                    cat eks-deploy-study.yml | grep image
                    
                    git status
                    git add eks-deploy-study.yml
                    git commit -m '[UPDATE] forest-back-study ${currentBuild.number} image versioning'
                    git push origin main
                    """
                }
            }
        }
    }
}
