def previousBuildNumber = currentBuild.previousBuild?.number

pipeline {
    agent any
    options {
        timeout(time: 1, unit: 'HOURS') // set timeout 1 hour
    }
    environment {
        DOCKER = 'sudo docker'

        TIME_ZONE = 'Asia/Seoul'
        PROFILE = 'local'
        
        // REPOSITORY_CREDENTIAL_ID = '${REPOSITORY_CREDENTIAL_ID}'
        // REPOSITORY_URL = '${REPOSITORY_URL}'
        TARGET_BRANCH = 'production-front'                
        
        // AWS_CREDENTIAL_NAME = '${AWS_CREDENTIAL_NAME}'
        // ECR_PATH = '${ECR_PATH}'
        // IMAGE_NAME = '${IMAGE_NAME}'
        REGION = 'ap-northeast-2'

        BUILD_NUM = '$BUILD_NUMBER'
        // PREVIOUS_TAG = ${previousBuildNumber}

        TARGET_FILE = 'eks-deploy-react.yml'        

    }
    stages{

        stage('Clone Repository') {
            steps {
                checkout scm
                echo 'Checkout Scm'
            }
        }

        stage('env setting') {
            steps{
                sh 'cp /var/jenkins_home/env/.env /var/jenkins_home/workspace/prod-front/forest-front'                
            }            
        }
        
        stage('dockerizing project by dockerfile') {
            steps {
                dir('forest-front') {
                    sh '''
                ls -al
                npm -v
                node -v
                 docker build -t $IMAGE_NAME:$BUILD_NUMBER .
                 docker tag $IMAGE_NAME:$BUILD_NUMBER $IMAGE_NAME:latest

                 '''
                }                
            }
            post {
                success {
                    echo 'success dockerizing project'
                }
                failure {
                    error 'fail dockerizing project' // exit pipeline
                }
            }
        }
        stage('upload aws ECR') {
            steps {
                script{
                    // cleanup current user docker credentials
                    sh 'rm -f ~/.dockercfg ~/.docker/config.json || true'
                    
                    sh 'echo ${ECR_PATH}'
                    sh 'echo ${REGION}'
                    sh 'echo ${AWS_CREDENTIAL_NAME}'
                   
                    docker.withRegistry("https://${ECR_PATH}", "ecr:${REGION}:${AWS_CREDENTIAL_NAME}") {
                      docker.image("${IMAGE_NAME}:${BUILD_NUMBER}").push()
                      docker.image("${IMAGE_NAME}:latest").push()

                      sleep 10
                    }

                }
            }
            post {
                success {
                    echo 'success upload image'
                    sh 'docker rmi ${IMAGE_NAME}:${BUILD_NUMBER}'
                    sh 'docker rmi ${IMAGE_NAME}:latest'
                }
                failure {
                    error 'fail upload image' // exit pipeline
                    sh 'docker rmi ${IMAGE_NAME}:${BUILD_NUMBER}'
                    sh 'docker rmi ${IMAGE_NAME}:latest'
                }
            }
        }

        stage('Manifest Update') {
            steps {
                git credentialsId: '${GITHUB_CREDENTIAL_ID}',
                    url: '${GITHUB_URL}',
                    branch: 'main'
                

                dir('front') {
                    sh 'ls -al'
                    echo '${previousBuildNumber}'
                    sh "sed -i 's/forest-front:${currentBuild.previousBuild?.number}/forest-front:${currentBuild.number}/g' eks-deploy-react.yml"
                    // sh "sed "$(grep -n 'image:' eks-deploy-react.yml | grep -Eo '^[^:]+')s/forest-front:${PREVIOUS_TAG}/forest-front:${BUILD_NUM}/g" ${TARGET_FILE}"
                    sh "git add ${TARGET_FILE}"
                    sh "git commit -m '[UPDATE] forest-front ${currentBuild.number} image versioning'"
                    sh "git push origin main"
                }
            }
        }
    }
}