version: "3"
services:
  application:
    image: ${FOREST_WORKBOOK_IMAGE}
    container_name: ${FOREST_WORKBOOK_CONTAINER}
    environment:
      KEY_STORE: ${KEY_STORE}
      KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD}
      KEY_STORE_TYPE: ${KEY_STORE_TYPE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MM_WEBHOOK_URL: ${MM_WEBHOOK_URL}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      KAKAO_AUTHORIZATION_GRANT_TYPE: ${KAKAO_AUTHORIZATION_GRANT_TYPE}
      KAKAO_CLIENT_NAME: ${KAKAO_CLIENT_NAME}
      KAKAO_CLIENT_AUTHENTICATION_METHOD: ${KAKAO_CLIENT_AUTHENTICATION_METHOD}
      JWT_REDIRECT_URI: ${JWT_REDIRECT_URI}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      GCP_LOCATION: ${GCP_LOCATION}
      GCP_ID: ${GCP_ID}
      GCP_BUCKET: ${GCP_BUCKET}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 9011:9011
    volumes:
      - /home/ubuntu/jenkins/env:/workbook
    restart: always
