server:
  port: 9002
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false

  data:
    mongodb:
      host: 13.124.81.117
      port: 27017
      authentication-database: admin
      username: root
      password: B105FOREST
      database: admin
      # uri: mongodb://localhost:27017/canvas


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forest?serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1234

notification:
  mattermost:
    enabled: true
    webhook-url: https://meeting.ssafy.com/hooks/j85wn7zntjbnjper47prr5icic
#    webhook-url: https://meeting.ssafy.com/hooks/pnorjom5sb87uy583c1zrqtjoa
    channel :